{{- range .Values.namespaces }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ . }}
  labels:
    kubernetes.io/metadata.name: {{ . }}
    project: infix
    environment: {{ $.Values.environment }}
    owner: {{ $.Values.owner }}
---
{{- end }}
