apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blog.fullname" . }}-secret
  labels:
    {{- include "blog.labels" . | nindent 4 }}
  annotations:
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: blog
type: Opaque
data:
  {{- toYaml .Values.secretData | nindent 2 -}}

---
{{- if .Values.customSecretEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blog.fullname" . }}-image-pull-secret
  labels:
    {{- include "blog.labels" . | nindent 4 }}
  annotations:
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: blog
type: Opaque
data:
  {{- toYaml .Values.imageSecretData | nindent 2 -}}
{{- end }}
